#!/bin/sh
#
# A hook script to compile the PDF and add it to the commit

set -e
if [ ! -z "$(git diff HEAD --name-only latex/)" ]
then
  latexmk -cd -outdir=.. -pdf ./latex/main.tex
  git add ./main.pdf
fi
